apiVersion: v1
kind: Service
metadata:
  name: mobile-simulator-service
  labels:
    app: mobile-simulator
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      name: http
  selector:
    app: mobile-simulator
